export const GET_HISTORY = "GET_HISTORY";
export const GET_FILTERED_HISTORY = "GET_FILTERED_HISTORY";
export const GET_ADDRESS = "GET_ADDRESS";
export const GET_FILTERED_ADDRESS = "GET_FILTERED_ADDRESS";
